### ISSUE TITLE
its crash game on start

### ISSUE THREAD

**Issue by kosavsech** [offyerrocker/PD2-Console#1]
Application has crashed: C++ exception
FindFirstFile() failed

-------------------------------

Callstack:

                       WSOCK32  (???)     socket                                              
                       WSOCK32  (???)     socket                                              
                       WSOCK32  (???)     socket                                              
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlSetLastWin32Error                                
                         ntdll  (???)     RtlAllocateHeap                                     
                         ntdll  (???)     LdrCallEnclave                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     NvOptimusEnablement                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                        func()  @mods/Console/lua/menumanager.lua:37                
                        Call()  @mods/base/req/core/Hooks.lua:109                   
                    origfunc()  @mods/base/lua/LocalizationManager.lua:8            
                        init()  @mods/The                                           
                                Fixes/localizationmanager.lua:10                    
                         new()                                                      
core/lib/utils/coreclass.lua:35  core/lib/setups/coresetup.lua:360                   

-------------------------------

**Comment by offyerrocker** [comment]
Thanks for your report. I've just released a new update that should fix this particular crash; please apply the update and try again.

**Comment by kosavsech** [comment]
> Thanks for your report. I've just released a new update that should fix this particular crash; please apply the update and try again.

Application has crashed: C++ exception
mods/Console-master/lua/menumanager.lua:35: attempt to index global 'Console' (a function value)



SCRIPT STACK

Call() @mods/base/req/core/Hooks.lua:109
origfunc() @mods/base/lua/LocalizationManager.lua:8
init() @mods/The Fixes/localizationmanager.lua:10
new() core/lib/utils/coreclass.lua:35
core/lib/setups/coresetup.lua:360


-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     zip_get_name                                        


-------------------------------

Current thread: Main
Script stack:
                        Call()  @mods/base/req/core/Hooks.lua:109                   
                    origfunc()  @mods/base/lua/LocalizationManager.lua:8            
                        init()  @mods/The                                           
                                Fixes/localizationmanager.lua:10                    
                         new()                                                      
core/lib/utils/coreclass.lua:35  core/lib/setups/coresetup.lua:360                   

-------------------------------

**Comment by offyerrocker** [comment]
Please ensure that the Console folder is just named `Console` without any hyphens, as hyphens are liable to break the mod.
In addition, make sure that you have BeardLib properly installed.

**Comment by kosavsech** [comment]
yes it helped now its working fine
